# This file contains test data for categories in YAML format.
# Test: Category foo inexsitent
categories:
  - id: "light"
    category_id: "services"
    name: "Electricidad"
    description: "Servicios de electricidad y energía."
  - id: "water"
    category_id: "services"
    name: "Agua"
    description: "Servicios de suministro de agua potable."
  - id: "gas"
    category_id: "foo"
    name: "Gas"
    description: "Servicios de suministro de gas natural y propano."