categories:
  - id: "light"
    category_id: "services"
    name: "Electricidad"
    description: "Servicios de electricidad y energía."
  - id: "water"
    category_id: "services"
    name: "Agua"
    description: "Servicios de suministro de agua potable."
  - id: "gas"
    category_id: "services"
    name: "Gas"
    description: "Servicios de suministro de gas natural y propano."
  - id: "kiner_garden"
    category_id: "schools"
    name: "Jardín de infancia"
    description: "Instituciones educativas para niños pequeños."
  - id: "fuel"
    category_id: "transport"
    name: "Combustible"
    description: "Estaciones de servicio y suministro de combustible."
  - id: "public_transport"
    category_id: "transport"
    name: "Transporte público"
    description: "Opciones de transporte público como autobuses, trenes y metro."
  - id: "supermarkets"
    category_id: "food"
    name: "Supermercados"
    description: "Tiendas de venta al por menor de alimentos y artículos del hogar."
  - id: "delivery"
    category_id: "food"
    name: "Entrega a domicilio"
    description: "Servicios de entrega de alimentos y artículos del hogar a domicilio."